### ISSUE TITLE
Common matrix interface?

### ISSUE THREAD

**Issue by mikera** [incanter/incanter#117]
Hello,

Would there be interest in the Incanter project in working towards a common interface for vector / matrix maths in Clojure?

The potential idea is to create an API / abstraction for matrix maths that is fairly generic and will support multiple possible matrix maths implementations (e.g. pure Java vs. JBLAS  vs. Colt vs. some other custom format used by an external program).

This would free projects like Incanter from having to fix on a specific matrix implementation, and allow generic matrix functionality to be developed on a common base that is useful across the Clojure landscape. 

I believe Clojure protocols are fast enough that performance would not be a concern.

See this thread in the Clatrix project: https://github.com/tel/clatrix/issues/7

Obviously, Incanter would be a big and important consumer of such an API / abstraction so wanted to test for interest in the Incanter project before deciding if this is a project worth committing effort to.

**Comment by xsyn** [comment]
Does this: https://github.com/incanter/incanter/issues/336 Close this issue?
