### ISSUE TITLE
set-stroke does not work on xy-plot with more than one line

### ISSUE THREAD

**Issue by aesnault** [incanter/incanter#131]
in this example set-stroke in only applied to the series 0
and (set-stroke :series 1... ) seems to have no effect

``` clojure
   (doto (xy-plot [1 2 3 4] [10 20 5 35])
     (add-lines [1 2 3 4] [20 5 30 15])
     (set-stroke :width 4 :dash 5)
     (set-stroke :series 1 :width 2 :dash 10)
     view) 
```

same behabiour with set-stroke-color
while with line-chart there is no problem 

``` clojure
    (doto (line-chart [:a :b :c :d] [10 20 5 35])
      (add-categories [:a :b :c :d] [20 5 30 15])
      (set-stroke :width 4 :dash 5)
      (set-stroke :series 1 :width 2 :dash 10)
      view)
```

**Comment by nblumoe** [comment]
We also still have an open issue for that over here: https://github.com/incanter/incanter/issues/233

**Comment by nbeloglazov** [comment]
Yes, it would be great. Seems like all other add-* functions add new data to existing datasets and don't create new ones, only `add-lines` and `add-points` are special in that sense. Also `add-lines` originally worked as expected (didn't create dataset): 01fed0d5f8cf9dc5b28c96d8cf5819657c23ed19, but David changed it fix some bug. It would be good to know what the bug was.

**Comment by nblumoe** [comment]
Okay, I am going to put it on my agenda then. One a related note: I stumbled upon this when using `time-series-plot` with `:group-by`. I also had to use `:dataset` then instead of `:series`. This is different from other plot types, so I am going to investigate this, too.

**Comment by mars0i** [comment]
This affects `set-stroke-color`, too, btw.

(The docstrings for `set-stroke` and `set-stroke-color` don't explain what a series is, anyway.  I guessed right about the meaning, but then when `:series`, it's hard to know what it means.  Very confusing.  I'm going to file an issue suggesting improving the docstring for these functions, and in that case, :dataset can be mentioned as well as `:series`.  I'll try adding a patch, if no one else does it first, when I get a chance.)
