### ISSUE TITLE
Better ways to find least-squares and min-norm solutions of AX=B

### ISSUE THREAD

**Issue by fasiha** [incanter/incanter#163]
This R user's complaint about Incanter [1] isn't 100% accurate but is entirely valid:  the only way to get least squares solutions of AX=B is to do so explicitly, i.e., `(solve (mmult (trans A) A) B)` or explicitly code one of the other, better, ways to do it (QR decomposition, SVD, etc.). 

Since Incanter uses clatrix which uses jblas, and since jblas provides a least squares and minimum norm solver for AX=B using the SVD via org.jblas.Solve.solveLeastSquares [2], it may be a good idea to provide this or similar functionality in Incanter.

In fact, I submitted a pull request to clatrix wrapping this very jblas method (with the hope of then providing it in incanter-core) but haven't heard anything about it yet from them [3].

Please advise me on the right way to add such functionality to Incanter, especially if Incanter's goal is to be matrix-library-agnostic.

[1] http://gray.clhn.co/blog/2013/04/10/clojure/
[2] https://github.com/mikiobraun/jblas/blob/master/src/main/java/org/jblas/Solve.java#L46
[3] https://github.com/tel/clatrix/pull/33

**Comment by MawiraIke** [comment]
Seems like this issue is outdated? It seems like Incanter now uses ```clojure.core.matrix.linear/least-squares``` which uses ```jblas``` v1.2.3
