### ISSUE TITLE
Problems with libgfortran3 dependency on 64-bit linux

### ISSUE THREAD

**Issue by gfredericks** [incanter/incanter#234]
I've had trouble satisfying the fortran dependency as outlined in the [jblas wiki](https://github.com/mikiobraun/jblas/wiki/Missing-Libraries).

In particular, on two different 64-bit ubuntu machines I can successfully `apt-get install libgfortran3` and yet this call still fails and prints the link to the jblas wiki page:

``` clojure
(incanter.stats/linear-model [1 2 3] [4 5 6])
```

**Comment by alexott** [comment]
In this case, change the system property `java.io.tmpdir` to point to your home dir, or other location..
