### ISSUE TITLE
Question: release version

### ISSUE THREAD

**Issue by malloc82** [incanter/incanter#285]
I see from commit messages the last release version is 1.5.6, and there is also a 1.5.7 snapshot. But in clojars.org there is 1.9.0. So is 1.9.0 referring to 1.5.7 snapshot?

**Comment by alexott** [comment]
Hello

The 1.5.6 is the some kind of "stable version" of Incanter in the `master`
branch.  The 1.9.0 is released from `develop` branch & contains many
breaking changes related to better integration with core.matrix, etc. Here
is the more details:
http://data-sorcery.org/2014/12/28/first-preview-of-incanter-2-0-aka-incanter-1-9-0/

On Sun, Jan 18, 2015 at 4:50 AM, Ritchie Cai <notifications@github.com>
wrote:

> I see from commit messages the last release version is 1.5.6, and there is
> also a 1.5.7 snapshot. But in clojars.org there is 1.9.0. So is 1.9.0
> referring to 1.5.7 snapshot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/incanter/incanter/issues/285>.
>



-- 
With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Comment by malloc82** [comment]
Ok, I see, I missed that. So if I want to fork and submit pull request, should my changes based on master or develop branch? Or it doesn't matter?

**Comment by alexott** [comment]
This matter. All changes should go to develop branch...

On Sun, Jan 18, 2015 at 5:56 PM, Ritchie Cai <notifications@github.com>
wrote:

> Ok, I see, I missed that. So if I want to fork and submit pull request,
> should my changes based on master or develop branch? Or it doesn't matter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/incanter/incanter/issues/285#issuecomment-70415711>.
>



-- 
With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Comment by malloc82** [comment]
Ok, got it. Thanks.
