### ISSUE TITLE
how to try out the develop branch?

### ISSUE THREAD

**Issue by aaelony** [incanter/incanter#290]
I'd like to try out the develop branch (with core.matrix support) and I imagine (?) I'd need to build the uberjars for the modules and then set it up as a local repo in a test project... Is there documentation on how best to do this or does anything like this exist?

Cheers,
Avram

**Comment by nblumoe** [comment]
Incanter v1.9.0 is available on clojars: https://clojars.org/incanter/incanter-core

**Comment by aaelony** [comment]
nblumoe - very nice, thank-you. (I'm also still interested in learning about how to test nascent versions as well)

**Comment by nblumoe** [comment]
@aaelony did you try the instructions in the README already? That should work: https://github.com/incanter/incanter/tree/develop#building-incanter

**Comment by aaelony** [comment]
@nblumoe thanks for this, I'm all set.  I was only missing "lein modules install" :)

**Comment by nblumoe** [comment]
Cool. Don't forget to send bug reports and/or pull requests! ;)

**Comment by aaelony** [comment]
Cool. Maybe this is interesting for computing column percentages? https://github.com/mikera/core.matrix/issues/221

```clojure
(defn column-percentages
     "Takes a Vector of Vectors containing integers, converts to a Matrix, computes column percentages."
     [m]
     (let [cols  (m/columns m)
           col-sums (mapv m/esum cols)]
       (m/div m col-sums)))
```
