### ISSUE TITLE
Get tests for `incanter.core/view` multimethod

### ISSUE THREAD

**Issue by nblumoe** [incanter/incanter#291]
I would like to add test for the `incanter.core/view`  multimethod. This method renders a `JFrame`  in the end and to do so it does some data massaging and conversion (for example https://github.com/incanter/incanter/blob/develop/modules/incanter-core/src/incanter/core.clj#L2629).

I suggest to extract the data conversions into separate functions which can then be tested independently from the `JFrame`  rendering. This already is the case for datasets, see https://github.com/incanter/incanter/pull/288#issuecomment-71913531).

Other suggestions or should I go with this approach?

Remaining question: Do we want to test the `JFrame`  rendering, too? I think that should not be part of Incanter's unit tests.

**Comment by nblumoe** [comment]
Guys, thoughts about this? If no one would like to see another approach I would start working on this.

**Comment by mikera** [comment]
Sounds sensible in general. 

I think some consideration should be given for the full range of types e.g. what happens to an unknown array type? I assume we need something like a default method that checks for `clojure.core.matrix/shape` and handles the type appropriately.
