### ISSUE TITLE
$map method not working in Incanter 1.9.0

### ISSUE THREAD

**Issue by ducky427** [incanter/incanter#298]
Hello,
I am trying to use the `$map` method of `incanter.core`.

When I tried the code for the method as given in the documenation,

```clojure
(use '(incanter core datasets))
(def cars (get-dataset :cars))

($map (fn [s] (/ s)) :speed cars)
```

I get this error:

```
NullPointerException   clojure.lang.Numbers.ops (Numbers.java:961)
```

I tried the next example 

```clojure
  ($map (fn [s d] (/ s d)) [:speed :dist] cars)
```

and again I got a NPE.

Any help would be appreciated.

Thanks

**Comment by Gerrrr** [comment]
Thank you for the report!
It is fixed in the development branch.
