### ISSUE TITLE
Is there a convenient way to read non-utf8 encoding csv file into Incanter?

### ISSUE THREAD

**Issue by SageHan** [incanter/incanter#300]
It seems Incanter can only recognize utf-8 encoding file while native clojure  `slurp` can read non-utf8 encoding file with `:encoding` keyword, So is there a convenient way to read non-utf8 encoding csv file into incanter dataset with the help of `slurp`?

**Comment by alexott** [comment]
you can use something like:

    (read-dataset (InputStreamReader. (FileInputStream. "data/co2.csv") "ISO-8859-1"))
