### ISSUE TITLE
API documentation link on incanter.org is 404'ed

### ISSUE THREAD

**Issue by mars0i** [incanter/incanter#323]
I don't know whether it makes sense to post this as an issue on the github repo, but I thought it wouldn't hurt.  http://data-sorcery.org/contents 's link to "API Documentation" goes to http://liebke.github.com/incanter , which doesn't exist at present.  It looks like it's been in this state for a couple of weeks now.  Thanks!

**Comment by alexott** [comment]
thank you for report, fixed!
