### ISSUE TITLE
allow svg exporting as string

### ISSUE THREAD

**Issue by carocad** [incanter/incanter#333]
hey guys,
I saw that you have added the ability for incanter to export charts as SVG files [here](https://github.com/incanter/incanter/tree/master/modules/incanter-svg/src/incanter). I would like to know if you could support outputting the svg content as a string instead of as a file.

The reason is that this would enable the use of inline dynamic svg charts in Lighttable ([see here](https://github.com/carocad/nerdy-painter)). There has also been a similar approach for Emacs [here](http://blog.brunobonacci.com/2016/03/18/emacs-incanter-hack/).

Let me know your thoughts on this

**Comment by alexott** [comment]
Per documentation & implementation "As with incanter.core/save, a java.io.OutputStream can be used in place of a filename." - this mean that you can use ByteArrayOutputStream instead of filename, and then convert output into String
