### ISSUE TITLE
Question about the latest version

### ISSUE THREAD

**Issue by ricardojmendez** [incanter/incanter#339]
Ran into something that might be a bug. I downloaded the latest repository to write a test case against it, but can't run `lein test`:

```
Could not find artifact incanter:incanter-core:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-io:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-charts:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-mongodb:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-pdf:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-svg:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-latex:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-excel:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-sql:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact incanter:incanter-zoo:jar:1.5.8-SNAPSHOT in clojars (https://clojars.org/repo/)
```

I'm not sure where to get those versions to build them, since the only public repository under incanter is this one.

**Update:** Found the corresponding subprojects under the `modules` folder. My question about which one is the most up-to-date stable version remains, since while I do get an issue with 1.5.7 I don't get it with the older 1.9.0.

**Comment by ricardojmendez** [comment]
I'm wondering now if 1.5.7 is the latest stable.  On Clojars I found 1.9.0, but it predates 1.5.7 by well over a year.  Branch `develop` is actually 1.9.1-SNAPSHOT.

Any pointers about which is the latest stable would be welcome.

**Comment by mikera** [comment]
1.9.0 is the latest official release. 1.5.7 is a bugfix release on the old 1.5 branch.

We don't really have an active maintainer for Incanter right now... I help out where I can but don't have time to maintain Incanter as well as all my other stuff. Ideally we should make a 1.9.1 release soon.

**Comment by ricardojmendez** [comment]
Thanks for the reply @mikera. Closing the issue.

My only suggestion would be making it obvious that 1.9.0 is the latest - I couldn't find what the latest version was on the site, so checked the README and thought it was 1.5.7.

Cheers!
