### ISSUE TITLE
incanter.core/save for dataset does not work (1.9.1 version in clojars)

### ISSUE THREAD

**Issue by chunsj** [incanter/incanter#341]
(use '(incanter core io datasets))
(def iris (get-dataset :iris))
(save iris "iris.csv")

Above code emits following error;

Unhandled java.lang.ClassCastException
   clojure.core.matrix.impl.dataset.DataSetRow cannot be cast to
   clojure.lang.IFn

```
                io.clj:  140  incanter.io/fn
                io.clj:  124  incanter.io/fn
           RestFn.java:  425  clojure.lang.RestFn/invoke
          MultiFn.java:  233  clojure.lang.MultiFn/invoke
```

boot.user5475539035458351755.clj:   28  ats.core/eval35395

**Comment by mikera** [comment]
Hmmmm incanter.io is pretty broken from what I can see.... doesn't even seem to handle delimiters correctly for CSV format. @shark8me this might explain some of the problems you were having.

I think this should be rewritten, probably to use `org.clojure/data.csv`

**Comment by alexott** [comment]
fixed in current version of code, will cut release soon
