### ISSUE TITLE
$order does not work on 1.9.1

### ISSUE THREAD

**Issue by chunsj** [incanter/incanter#342]
The code expects rows in dataset be a map, however in 1.9.1, this is not true and emits java.lang.AbstractMethodError.

As far as I know 1.9.1 is under heavy development, 
so, if submitting this kind of bugs bugging development process, let me know, then 
I'll keep calm and just wait. :-)

**Comment by mikera** [comment]
Thanks for the report! Will take a look if I get time.

**Comment by alexott** [comment]
fixed
