### ISSUE TITLE
Incompatible Licenses on develop branch

### ISSUE THREAD

**Issue by benkamphaus** [incanter/incanter#350]
The develop branches, which I'm assuming is the source of the [1.9.1 jar on Clojars](https://clojars.org/incanter), includes [`vectorz-clj`](https://github.com/mikera/vectorz-clj) as a dependency, but `vectorz-clj` is LGPL licensed. This makes it incompatible with the [Eclipse Public License](https://eclipse.org/legal/eplfaq.php#3RDPARTY).

**Comment by mikera** [comment]
Hi @benkamphaus 

vectorz-clj is my project. 

It is fine to use as a libraryfor Incanter - the LGPL allows use as a library in any other project (including proprietary code). The only incompatibility would be if you directly copied code between Incanter and vectorz-clj (in which case you would need permission from the author of that code to release it under the other license).

**Comment by benkamphaus** [comment]
This is not a correct interpretation of the impact of including LGPL in the library. See specifically (in the [GNU statement](https://www.gnu.org/licenses/lgpl-java.en.html)):

> If you distribute a Java application that imports LGPL libraries, it's easy to comply with the LGPL. Your application's license needs to allow users to modify the library, and reverse engineer your code to debug these modifications.

and:

> When you distribute the library with your application (or on its own), you need to include source code for the library.

See also this statement from the [Apache foundation](http://www.apache.org/legal/resolved.html#category-x) which goes into more detail, ensuring that licenses:

> must not place restrictions on the distribution of larger works, other than to require that the covered component still complies with the conditions of its license.

To which they identify the LGPL as an exception:

> The LGPL is ineligible primarily due to the restrictions it places on larger works, violating the third license criterion.

More specifically, you should read and be familiar with the terms of the LGPL in [section 6](https://www.gnu.org/licenses/lgpl-2.1.html#SEC3), which are why the ASL and EPL FAQs expressly forbid the inclusion of LGPL libraries.

**Comment by mikera** [comment]
I'm not a lawyer but I still don't see the problem. Incanter does not include any LGPL code, it is just a library dependency. 

If you redistribute a combined application you will need to comply with the relevant licenses for the relevant portions, but this is not incompatible. See e.g. this answer which states that LGPL and EPL libraries can be used together in the same project:

http://opensource.stackexchange.com/questions/2486/compatibility-between-epl-and-lgpl

Obviously, if the Apache foundation wishes to disallow the use of LGPL code in their own projects as a matter of policy, they are free to do so.

**Comment by benkamphaus** [comment]
@mikera

The question you cite does not handle this case in detail. The issue is that Incanter is not a one-off open source project as discussed , it's a _library_. That means people will see the project is EPL licensed and think they can redistribute it under those terms. Including `vectorz-clj` makes this no longer true, they must now also comply with the additional provisions stipulated by the LGPL.

This is why the APL and EPL FAQs say these licenses are incompatible in the first place. If you're going to go against the accepted knowledge, I'd suggest you consult with a lawyer.

**Comment by mikera** [comment]
Incanter is fully EPL licensed. 

It does not "include" vectorz-clj. vectorz-clj is an optional dependency: Incanter should work with any fully conformant core.matrix implementation (see the test suite).

The LGPL really only becomes relevant when someone builds *and distributes* a solution that includes both Incanter and vectorz-clj. I shall add a note to that effect to the Incanter README.

**Comment by mobileink** [comment]
On Sep 21, 2016 6:25 PM, "Mike Anderson" <notifications@github.com> wrote:
>
> Incanter is fully EPL licensed.
>
> It does not "include" vectorz-clj. vectorz-clj is an optional dependency:
Incanter should work with any fully conformant core.matrix implementation
(see the test suite).

In other words, if I want to use vector-clj with incanter I must obtain it
separately?
i.e. it does not come with the incanter download/clone?
>
> The LGPL really only becomes relevant when someone builds and distributes
a solution that includes both Incanter and vectorz-clj. I shall add a note
to that effect to the Incanter README.

**Comment by benkamphaus** [comment]
@mikera This is [not true at present on the develop branch](https://github.com/incanter/incanter/blob/develop/modules/incanter-core/project.clj#L14) which is the reason I filed this issue.

**Comment by mikera** [comment]
That's just a dependency - it doesn't mean that any vectorz code is directly included in the Incanter source.

It should be possible to :exclude vectorz-clj in your project.clj if you wish. If there is some hard-wired requirement for vectorz-clj I'd take a patch to fix that (Incanter is intended to work with any core.matrix implementation)

**Comment by benkamphaus** [comment]
@mikera I've consistently and clearly presented what the issue is: the inclusion of the LGPL licensed _dependency_ makes it so that Incanter can't be _redistributed_ under EPL terms. I have not said that it includes `vectorz-clj` _code_, nor have I suggested the project somehow precludes a workaround or way to exclude it.

I don't know why you've opted to litter the Clojure Data Science landscape with LGPL land mines, but it's your freely given labor and your prerogative to license the fruits thereof how you wish. I would however (based on this conversation) suggest reading up on the LGPL and its terms so as to better understand the implications of using it.

I have tried to be patient while this issue has been handled flippantly and hurriedly. Thus far you have:

1. Preemptively closed this issue (it is _not_ resolved).
2. Stated that there is no issue if code isn't directly copied (this is false, as I pointed out by referring you to section 6 of the LGPL).
3. Stated falsely that core-matrix is an optional dependency the user must specify, when instead it's a hard-coded dependency the user must exclude (as of now, on the develop branch).

If there's another project maintainer who can assess this, I'd ask you to please defer to them to avoid the conflict of interest around the library's inclusion as a dependency.

**Comment by mikera** [comment]
I simply disagree that LGPL is a "land mine". You are entirely free, as a user of an LGPL library, to use it and redistribute it as you wish providing you comply with the license whenever you redistribute the library.

I'm pretty familiar with the relevant licenses. Please see section 5 of the LGPL, re: a "work that uses the Library". I consider Incanter to be a "work that uses the library". As such, Incanter itself is not affected by the LGPL. You can redistribute Incanter without vectorz-clj with no concerns.

I prefer the LGPL to the EPL in general (my main concerns are having weak copyleft and GPL compatibility), and will continue to use it unless I have a strong reason otherwise (e.g. core.matrix itself uses the EPL because it is becoming part of Clojure contrib)

To address your points:
1. As above, Incanter is not affected by the LGPL. It is a "work that uses the library". Hence I believe it is appropriate to close this issue.
2. I don't see these terms as being difficult to comply with, even if you do create and distribute a derivative work including portions of vectorz-clj.
3. I haven't tested it, but the intention is that it can be safely excluded. Incanter should work without it, which is why I describe it as "optional". Patches welcome to make this work.

I have no particular vested interest re: the inclusion of vectorz-clj, I just want Incanter to have a good numerical matrix library implementation. And currently vectorz-clj is by far the best pure-JVM library available for Clojure.

Why are you so interested in this issue? Is there something specific you are trying to achieve? Maybe I can help you if that is the case.

**Comment by benkamphaus** [comment]
> I simply disagree that LGPL is a "land mine". You are entirely free, as a user of an LGPL library, to use it and redistribute it as you wish providing you comply with the license whenever you redistribute the library.

"provided you comply with the license..." -- that's precisely the point. Re (2) -- it makes no difference to me whether or not you believe those terms are difficult to comply with, they are *not the terms of the EPL*. This is essentially the principle of least surprise for licensing.

Re: (1) and (3), and your section above, if it's specifically excluded, yes, it is _possible_ (though not the naive use case) that Incanter could be distributed without the LGPL `vectorz-clj` jar and be subject to clause (5) and not clause (6). My point is today if you add Incanter as a dep in your project.clj and don't exclude anything and redistribute an application that depends on it, you will be in violation of the LGPL unless you take additional steps to comply with the LGPL's license. This is a "land mine" because it's an unexpected change in what you must do to comply with the licenses of your libraries, all because you added a dependency which you thought was EPL and safe to use.

Re: my goals -- I want to retain as much flexibility as possible re: future use of any Clojure data sci code I produce . My preference would be for common licensing practices so that the same license or family of licenses would be in use across projects that are typically combined or depend on each other (as is the case with core Python data sci libraries like pandas, numpy, scipy, sklearn, etc.). I don't want to take the cartesian product of every library author's opinion and hope everything checks out if a client gets acquired and subjected to compliance audits, or if I have to distribute the software in something like an app store model that's fundamentally incompatible with the LGPL.

Barring that, I at least want the LGPL portions of the ecosystem to be opt in for libraries like Incanter and `core.matrix` (where `vectorz-clj` is [correctly cordoned off in the dev profile](https://github.com/mikera/core.matrix/blob/806de28cf2264bc3a51ae2a0f5de62564b7da077/project.clj#L14)).

**Comment by mikera** [comment]
Right, you can't redistribute vectorz-clj under the EPL. I understand that. But it doesn't stop you using Incanter with vectorz-clj for data science work, or indeed redistributing the result as long as you comply with relevant licenses.

I agree with the principle of keeping flexibility in the Clojure ecosystem. In practice though I believe you will always need to do a check on licenses if you intend to redistribute open source code (there's even a lein plugin to do this: https://github.com/technomancy/lein-licenses)

I guess it would be fine to put vectorz-clj in the dev profile, as long as it doesn't affect the "out of the box" experience.
