### ISSUE TITLE
1.9.1 release on clojars is broken, dev branch build should be on clojars

### ISSUE THREAD

**Issue by joinr** [incanter/incanter#369]
I went to migrate from incanter 1.5.8 to 1.9.1, and got tripped up by an (apparently fixed in dev branch) dependency resolution error for an ancient version of clojure 1.3 (part of a transitive dependency via swingrepl...).

To get things working, I built the dev branch for incanter and deployed a 1.9.1-SNAPSHOT artifact under my group on clojars (joinr/incanter "1.9.1-SNAPSHOT") .  This is just a shim...

Can anyone with access to the incanter group on clojars either a) push a new 1.9.1. release or b) push a 1.9.2. SNAPSHOT [or release...] (built from the current dev branch)?

**Comment by dupuchba** [comment]
same problem here, I'd love to use clojure 1.9* with incanter but I can't

**Comment by alexott** [comment]
I'll try to push 1.9.2 this week...

**Comment by dupuchba** [comment]
@alexott I am new to incanter but I have some time next week, if I can help I'll be glad

**Comment by include** [comment]
Hi, incanter/clojure newbie here...

Are you guys talking about this error?

```
include@Franciscos-MacBook-Air ~/Documents/dev/clojure/incanter $ lein repl
Retrieving incanter/incanter/1.9.1/incanter-1.9.1.pom from clojars
Retrieving incanter/incanter-core/1.9.1/incanter-core-1.9.1.pom from clojars
Retrieving incanter/incanter-io/1.9.1/incanter-io-1.9.1.pom from clojars
Retrieving incanter/incanter-charts/1.9.1/incanter-charts-1.9.1.pom from clojars
Retrieving incanter/jfreechart/1.0.13-no-gnujaxp/jfreechart-1.0.13-no-gnujaxp.pom from clojars
Retrieving incanter/jcommon/1.0.16/jcommon-1.0.16.pom from clojars
Retrieving incanter/incanter-mongodb/1.9.1/incanter-mongodb-1.9.1.pom from clojars
Retrieving incanter/incanter-pdf/1.9.1/incanter-pdf-1.9.1.pom from clojars
Retrieving incanter/incanter-svg/1.9.1/incanter-svg-1.9.1.pom from clojars
Retrieving incanter/incanter-latex/1.9.1/incanter-latex-1.9.1.pom from clojars
Retrieving incanter/incanter-excel/1.9.1/incanter-excel-1.9.1.pom from clojars
Retrieving incanter/incanter-sql/1.9.1/incanter-sql-1.9.1.pom from clojars
Retrieving incanter/incanter-zoo/1.9.1/incanter-zoo-1.9.1.pom from clojars
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

**Comment by lcodes** [comment]
We're trying to upgrade to Clojure 1.9 too. Would definitely appreciate someone pushing 1.9.2 to clojars with this fix https://github.com/incanter/incanter/pull/354 (that lone `&` is causing the defn spec to fail during compilation of incanter/core.clj)

**Comment by alexott** [comment]
I just put 1.9.2 to clojars - please try it & re-open this issue if it doesn't work...

**Comment by joinr** [comment]
Just to close the loop, I migrated to 1.9.2 and it appears to be good so far.

**Comment by alexott** [comment]
Thank you for confirmation @joinr - I have slightly more time now to work in Incanter...
