### ISSUE TITLE
scatter-plot-matrix broken since 1.5.7

### ISSUE THREAD

**Issue by joinr** [incanter/incanter#377]
Actual scatter-plots fail to render in 1.9.2.  Histograms render fine.
Working theory: the dataset implementation invalidated old-school direct access to the :rows key of the dataset (it was just a map of :col-names and :rows).  This may have broken backwards compatibility in some of the querying internal to the gigantic incanter.charts/scatter-plot-matrix*  constructor.

**Comment by joinr** [comment]
Confirmed.  There's keyword access via (:rows ...) at line 1611.  This causes a return of nil against the core.matrix dataset implementation, leading to a 0 itemcount for the jfreechart AbstractDataSet.
Patched (:rows ...) to (clojure.core.matrix.dataset/row-maps ...) fixes it.

I'll submit a pr with said patch this pm.

**Comment by alexott** [comment]
closed via #384
