### ISSUE TITLE
Incanter doesn't respect "user.dir" property?

### ISSUE THREAD

**Issue by stardiviner** [incanter/incanter#382]
I try to do:
```clojure
(System/setProperty "user.dir" "/path/to/another/dir")
```
But Incanter `save` does not save to this `/path/to/another/dir` by default.
Is it possible to make Incanter follow this?
I know Incanter can specify directory to save. But I'm writing a Emacs Org-mode package, need to change "current working directory". I need to let Incanter save generated plot under "current working directory". So have an ask here.

**Comment by joinr** [comment]
Just at a cursory glance: 

Chart saving is implemented via the save multimethod in incanter.charts, defined for JFreeChart objects.  The implementation wants an input called filename, "but" internally it's actually calling java.File. on the "filename" arg.  So, in theory, one could accomplish this by passing the absolute path for chart output as a value.  So, maybe trying to create the path as a function of the current value of user.dir (or the actual directory you're interested in) and the target file.  If you're doing this programmatically, as long as you can access the current working directory, you should be able to pass it to the save method as described.

More importantly: incanter is defaulting to java's interpretation of paths in this case.  I'm guessing (but haven't verified) that the java.io.File class is not respecting the current working directory, perhaps caching the initial value of user.dir (perhaps whatever the property was on class initialization).

**Comment by stardiviner** [comment]
Thanks for you hint. I have a clue how to implement it in my package now.

**Comment by joinr** [comment]
If this is resolved, do you mind closing por favor? Or maybe @alexott can close it.

**Comment by stardiviner** [comment]
@joinr Thanks, I did missed this issue.

**Comment by joinr** [comment]
For future reference, what's your org mode package?  I'm getting into org and may be a user...

**Comment by stardiviner** [comment]
@joinr It's in Org-mode `master` branch https://code.orgmode.org/bzg/org-mode/src/master/contrib/lisp/ob-clojure-literate.el already. And here is my developing repo used to get user issues and new testing features: https://github.com/stardiviner/ob-clojure-literate
