### ISSUE TITLE
Migrate root incanter project.clj to clojure 1.9, modules are already there.

### ISSUE THREAD

**Issue by joinr** [incanter/incanter#392]
It's not dire, but could be a "good thing" to bump the clojure dep up to 1.9.
I'm planning on trying this out in my fork to see what problems come, namely spec violations that got by in 1.8 from legacy code, but I think a lot of stuff has already been ironed out....

[edit] forgot to specify that this applies to the parent/root incanter project, which is still on 1.8.

**Comment by MawiraIke** [comment]
Looks like this is fixed and there is no issue.
