### ISSUE TITLE
(use '(incanter excel)) error

### ISSUE THREAD

**Issue by stardiviner** [incanter/incanter#400]
Load Incanter Excel in CIDER REPL:
```clojure
(use '(incanter core io excel))
```
I got error:

On Java 8, error

    Syntax error compiling at (incanter/excel/workbook.clj:21:24).
    Unable to find static field: BOLDWEIGHT_NORMAL in interface org.apache.poi.ss.usermodel.Font
    Syntax error compiling at (incanter/excel.clj:1:1).
    namespace 'incanter.excel.workbook' not found

On Java 11:

    Syntax error compiling at (incanter/excel/workbook.clj:21:24).
    Unable to find static field: BOLDWEIGHT_NORMAL in interface org.apache.poi.ss.usermodel.Font

    2. Unhandled clojure.lang.Compiler$CompilerException
       Error compiling incanter/excel.clj at (1:1)
       #:clojure.error{:phase :compile-syntax-check,
                       :line 1,
                       :column 1,
                       :source "incanter/excel.clj"}
                      core.clj: 5867  clojure.core/throw-if
                      core.clj: 5953  clojure.core/load-lib
                      core.clj: 5928  clojure.core/load-lib
                   RestFn.java:  142  clojure.lang.RestFn/applyTo
                      core.clj:  667  clojure.core/apply
                      core.clj: 5985  clojure.core/load-libs
                      core.clj: 5969  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  669  clojure.core/apply
                      core.clj: 6093  clojure.core/use
                      core.clj: 6093  clojure.core/use
                   RestFn.java:  436  clojure.lang.RestFn/invoke
                     excel.clj:    1  incanter.excel/eval30842/loading--auto--
                     excel.clj:    1  incanter.excel/eval30842
                     excel.clj:    1  incanter.excel/eval30842
                 Compiler.java: 7177  clojure.lang.Compiler/eval
                 Compiler.java: 7166  clojure.lang.Compiler/eval
                 Compiler.java: 7636  clojure.lang.Compiler/load
                       RT.java:  381  clojure.lang.RT/loadResourceScript
                       RT.java:  372  clojure.lang.RT/loadResourceScript
                       RT.java:  459  clojure.lang.RT/load
                       RT.java:  424  clojure.lang.RT/load
                      core.clj: 6126  clojure.core/load/fn
                      core.clj: 6125  clojure.core/load
                      core.clj: 6109  clojure.core/load
                   RestFn.java:  408  clojure.lang.RestFn/invoke
                      core.clj: 5908  clojure.core/load-one
                      core.clj: 5903  clojure.core/load-one
                      core.clj: 5948  clojure.core/load-lib/fn
                      core.clj: 5947  clojure.core/load-lib
                      core.clj: 5928  clojure.core/load-lib
                   RestFn.java:  142  clojure.lang.RestFn/applyTo
                      core.clj:  667  clojure.core/apply
                      core.clj: 5989  clojure.core/load-libs
                      core.clj: 5969  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  669  clojure.core/apply
                      core.clj: 6093  clojure.core/use
                      core.clj: 6093  clojure.core/use
                   RestFn.java:  408  clojure.lang.RestFn/invoke
                          REPL:   15  user/eval30836
                          REPL:   15  user/eval30836
                 Compiler.java: 7177  clojure.lang.Compiler/eval
                 Compiler.java: 7132  clojure.lang.Compiler/eval
                      core.clj: 3214  clojure.core/eval
                      core.clj: 3210  clojure.core/eval
                      main.clj:  437  clojure.main/repl/read-eval-print/fn
                      main.clj:  437  clojure.main/repl/read-eval-print
                      main.clj:  458  clojure.main/repl/fn
                      main.clj:  458  clojure.main/repl
                      main.clj:  368  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                      AFn.java:   22  clojure.lang.AFn/run
                   session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
                   session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                      AFn.java:   22  clojure.lang.AFn/run
                   Thread.java:  834  java.lang.Thread/run
    
    1. Caused by java.lang.Exception
       namespace 'incanter.excel.workbook' not found
    
                      core.clj:  667  clojure.core/apply
                      core.clj: 5985  clojure.core/load-libs
                      core.clj: 5969  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  669  clojure.core/apply
                      core.clj: 6093  clojure.core/use
                      core.clj: 6093  clojure.core/use
                   RestFn.java:  436  clojure.lang.RestFn/invoke
                     excel.clj:    1  incanter.excel/eval30842/loading--auto--
                     excel.clj:    1  incanter.excel/eval30842
                     excel.clj:    1  incanter.excel/eval30842
                 Compiler.java: 7177  clojure.lang.Compiler/eval
                 Compiler.java: 7166  clojure.lang.Compiler/eval
                 Compiler.java: 7636  clojure.lang.Compiler/load
                       RT.java:  381  clojure.lang.RT/loadResourceScript
                       RT.java:  372  clojure.lang.RT/loadResourceScript
                       RT.java:  459  clojure.lang.RT/load
                       RT.java:  424  clojure.lang.RT/load
                      core.clj: 6126  clojure.core/load/fn
                      core.clj: 6125  clojure.core/load
                      core.clj: 6109  clojure.core/load
                   RestFn.java:  408  clojure.lang.RestFn/invoke
                      core.clj: 5908  clojure.core/load-one
                      core.clj: 5903  clojure.core/load-one
                      core.clj: 5948  clojure.core/load-lib/fn
                      core.clj: 5947  clojure.core/load-lib
                      core.clj: 5928  clojure.core/load-lib
                   RestFn.java:  142  clojure.lang.RestFn/applyTo
                      core.clj:  667  clojure.core/apply
                      core.clj: 5989  clojure.core/load-libs
                      core.clj: 5969  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  669  clojure.core/apply
                      core.clj: 6093  clojure.core/use
                      core.clj: 6093  clojure.core/use
                   RestFn.java:  408  clojure.lang.RestFn/invoke
                          REPL:   15  user/eval30836
                          REPL:   15  user/eval30836
                 Compiler.java: 7177  clojure.lang.Compiler/eval
                 Compiler.java: 7132  clojure.lang.Compiler/eval
                      core.clj: 3214  clojure.core/eval
                      core.clj: 3210  clojure.core/eval
                      main.clj:  437  clojure.main/repl/read-eval-print/fn
                      main.clj:  437  clojure.main/repl/read-eval-print
                      main.clj:  458  clojure.main/repl/fn
                      main.clj:  458  clojure.main/repl
                      main.clj:  368  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                      AFn.java:   22  clojure.lang.AFn/run
                   session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
                   session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                      AFn.java:   22  clojure.lang.AFn/run
                   Thread.java:  834  java.lang.Thread/run

**Comment by campeterson** [comment]
I'm not sure which version of Incanter you are using, but this is working for me on Incanter `1.9.3`

```sh
clj \
-Sdeps '{:deps {incanter/incanter-core {:mvn/version "1.9.3"} incanter/incanter-excel {:mvn/version "1.9.3"}}}' \
-e '(ns stuff (:require [incanter.core :as core] [incanter.excel :as excel])) (core/view (excel/read-xls "http://incanter.org/data/aus-airline-passengers.xls"))'
```

**Comment by stardiviner** [comment]
I'm using `1.9.3` too. I run your command works fine too.

I load a clean clj REPL with:
```
clj \
-Sdeps '{:deps {incanter/incanter {:mvn/version "1.9.3"} incanter/incanter-excel {:mvn/version "1.9.3"}}}' \
--repl
```
Then
```clojure
(use '(incanter core io excel))
```
This works fine too.
Seems my environment somewhere config wrong. I will dig deeper. Thanks for your help. :)

**Comment by campeterson** [comment]
Glad to hear it's working for you. Let us know what you find.

**Comment by stardiviner** [comment]
It is conflict with another artifact `dk.ative/docjure    {:mvn/version "1.12.0"}`
