### ISSUE TITLE
Integers coerce to Floats when creating a dataset from an xls document

### ISSUE THREAD

**Issue by MawiraIke** [incanter/incanter#410]
I have created an xls document with only integers in its cells but when I read it using Incanters ```read-xls``` function, all the values/cells are coerced to floats. 

A previous issue #248 mentioned about integers being coerced to floats when creating a dataset from a map but it seems like that was fixed. I realized this while i was checking issue #273 which i think is still embodied in this issue.

Edit: This is not causing issues in my program but I'm just wondering why this happens, or if there is a way to prevent this from happening.

**Comment by MawiraIke** [comment]
Seems like there is a bug in the ```read-xls``` function. After altering my xls file to include other data types such as multiple-decimal floats, nil and some empty fields it seems like the dataset created contains a lot of wrong data as shown by the image below. The data on the left is the original data, the window shows incanters read dataset. 

![Real vs incanters data.](https://user-images.githubusercontent.com/38689046/69457806-f3782880-0d7e-11ea-8be8-449fe0f0a183.png)

**Comment by joinr** [comment]
Just perusing.  Yea, the underlying format in Excel is that everything is a float (I believe).  So values from apache POI are going to coerce to floats.  I handle this via some additional parsing by default.  I think there may be specifically tagged types of integers in Excel, but they're stored as floats maybe.

**Comment by MawiraIke** [comment]
Thank you for that. Seems like Apache POI doesnt have a supported Integer
[type](
https://poi.apache.org/apidocs/dev/org/apache/poi/hsmf/datatypes/Types.html
).
I would also be glad to know why Incanter yields wrong values when multiple
data types are used as mentioned above.

**Comment by MawiraIke** [comment]
I am going to close this issue because i cannot reproduce the wrong values error after trying with new excel files, even with multiple data types.
