### ISSUE TITLE
Set stroke color seems to have a bug on scatter plots.

### ISSUE THREAD

**Issue by MawiraIke** [incanter/incanter#415]
The ```set-stroke-color``` method seems to have a rather peculiar working on ```scatter-plot```s. I think its a bug but I am still finding out why. Using the following scatter plot, 

```clojure
(def mvn-samp (sample-mvn 1000 :mean [7 5] :sigma (matrix [[2 1.5] [1.5 3]])))
(def mvn-plot (scatter-plot (sel mvn-samp :cols 0) (sel mvn-samp :cols 1)))
;
(def x (sel mvn-samp :cols 0))
(def y (sel mvn-samp :cols 1))
(def lm (linear-model y x))

(doto mvn-plot
  ;; Only series 0 color is changed
  (add-lines x (:fitted lm))
  (set-stroke-color java.awt.Color/GREEN :series 0)
  (set-stroke-color java.awt.Color/BLUE :series 1)
  view
  )
```
you'd expect that the first series would be green and the second series would be blue but instead, only the first series changes its color. I.e. the color blue is not reflected.
Using
```clojure
(doto plot
  (add-categories ["a" "b" "c"] [5 25 40] :series-label "s2")
  ;;(set-stroke-color java.awt.Color/GREEN :series 0)
  (set-stroke-color java.awt.Color/RED :series 1)
  view
  )
``` 
instead of the first, i.e. changing only the second series, changes only the second series color as intended.

I have tried the same two implementations on the bar chart and the polar chart and it works.
```clojure
;; polar-chart
(def sample-plot (polar-chart [20 145 90] [45 120 150] :legend true))

(doto sample-plot
  (add-polar [[34 93] [83 03] [78 138]] :series-label "Data 2")
  ;;color changes appropriately if this is on or off.
  ;;(set-stroke-color java.awt.Color/GREEN :series 0)
  (set-stroke-color java.awt.Color/ORANGE :series 1)
  view
  )
```

```clojure
;;bar-chart
(def plot (bar-chart ["a" "b" "c"] [10 20 30] :legend true :series-label "s1"))

(doto plot
  (add-categories ["a" "b" "c"] [5 25 40] :series-label "s2")
  ;;color changes appropriately if this is on or off.
  ;;(set-stroke-color java.awt.Color/GREEN :series 0)
  (set-stroke-color java.awt.Color/RED :series 1)
  view
  )
```

I also checked the ```set-stroke``` method saw  that it has a bug too on the ```scatter-plot``` as mentioned in issue #233 but i don't know why. I am checking it to see why.

**Comment by MawiraIke** [comment]
I have also checked the ```add-lines``` method for ```scatter-plot```s and it seems like it implements the same method of adding data to the chart (By adding data to a series and then add the series to a dataset and then set the dataset of the chart to the new dataset) as the ```polar-chart``` even though the polar charts ```set-stroke-color``` works.

The ```polar-chart``` ```add-polar``` can be found at commit 15c84c94c49f0095d0c7f5840d9b9ec909ec5279

**Comment by alexott** [comment]
should be fixed now
