### ISSUE TITLE
Error when running Incanter on Docker

### ISSUE THREAD

**Issue by MawiraIke** [incanter/incanter#416]
I can't seem to  build the dockerfile in Incanters root project. I am using Incanter 1.9.4 and when i start the build, I get an error:

```
E: Unable to locate package libgfortran3
Error response from daemon: The command '/bin/sh -c apt-get update && apt-get -y install libgfortran3 && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by alexott** [comment]
It may depend on the version of distribution that you're using for Docker. Incanter needs fortran libraries - check how package is called now

**Comment by MawiraIke** [comment]
Thanks, I hadn't realized that, seems like i hadn't installed libgfortran3. 
I'm closing this issue.
